application: echo3-test
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

# For FriendConnect
- url: /rpc_relay.html
  static_files: templates/rpc_relay.html
  upload: templates/rpc_relay.html

- url: /canvas.html
  static_files: templates/canvas.html
  upload: templates/canvas.html
  
# Unit tests for API
- url: /testapi/.*
  script: testapi/main.py

# For FacebookConnect
- url: /xd_receiver.htm
  static_files: templates/xd_receiver.htm
  upload: templates/xd_receiver.htm

- url: /test/.*
  script: testpages.py

# Keep this last
- url: /.*
  script: main.py
