var SITE_ID = '02962301966004179520';
google.friendconnect.container.setParentUrl('/');

var REVIEW_SKIN = {};
REVIEW_SKIN['BORDER_COLOR'] = '#cccccc';
REVIEW_SKIN['ENDCAP_BG_COLOR'] = '#e0ecff';
REVIEW_SKIN['ENDCAP_TEXT_COLOR'] = '#333333';
REVIEW_SKIN['ENDCAP_LINK_COLOR'] = '#0000cc';
REVIEW_SKIN['ALTERNATE_BG_COLOR'] = '#ffffff';
REVIEW_SKIN['CONTENT_BG_COLOR'] = '#ffffff';
REVIEW_SKIN['CONTENT_LINK_COLOR'] = '#0000cc';
REVIEW_SKIN['CONTENT_TEXT_COLOR'] = '#333333';
REVIEW_SKIN['CONTENT_SECONDARY_LINK_COLOR'] = '#7777cc';
REVIEW_SKIN['CONTENT_SECONDARY_TEXT_COLOR'] = '#666666';
REVIEW_SKIN['CONTENT_HEADLINE_COLOR'] = '#333333';
REVIEW_SKIN['DEFAULT_COMMENT_TEXT'] = '- review this volunteering event -';
REVIEW_SKIN['HEADER_TEXT'] = 'Reviews';
REVIEW_SKIN['POSTS_PER_PAGE'] = '7';
