#application: servicefootprint
application: footprint2009dev
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /thirdparty
  static_dir: thirdparty

- url: /images
  static_dir: images

# For FriendConnect
- url: /rpc_relay.html
  static_files: templates/rpc_relay.html
  upload: templates/rpc_relay.html

- url: /canvas.html
  static_files: templates/canvas.html
  upload: templates/canvas.html

# Unit tests for API
- url: /testapi/.*
  script: testapi/main.py

# For FacebookConnect
- url: /xd_receiver.htm
  static_files: templates/xd_receiver.htm
  upload: templates/xd_receiver.htm

- url: /test/.*
  script: testpages.py

- url: /admin/.*
  script: main.py
  login: admin

- url: /export/.*
  script: export/main.py

# For Gadget
- url: /gadget.xml
  static_files: templates/gadget.xml
  upload: templates/gadget.xml

# autocompleter for search
- url: /autocomplete/.*
  script: autocomplete/main.py

# Keep this last
- url: /.*
  script: main.py
